### ISSUE TITLE
[Feature Request] Add support for xip.io hostnames

### ISSUE THREAD

**Issue by ollietreend** [FreedomBen/dory#11]
It'd be really useful if dory supported [xip.io virtual hostnames](http://xip.io/).

This would allow access to running containers from other devices on the LAN, which is really useful for example when testing web apps on mobile devices.

The project [Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) implements this in a really nice way. A similar approach here would work well, I think.

So, for example, I could have a container running with `VIRTUAL_HOST` of `example.docker`, and my host IP address is `192.168.0.10`. From a mobile device on the same network, I'd be able to access the container by going to `http://example.docker.192.168.0.10.xip.io` (since this would resolve to the host IP).

It looks like `dory-http-proxy` already binds to `0.0.0.0`, so the server will be accessible from other devices on the network.

The only missing piece is adding a xip.io hostname regex to each virtual host's `server_name` entry in the nginx configuration. Something like this should work ([inspired by VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/512e9eda3d09a14d71498f3dafe7d9116f4c7bc0/config/nginx-config/sites/default.conf#L78)):

```
server {
    server_name example.docker ~^example\.docker\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
}
```

**Comment by ollietreend** [comment]
This was easier to implement that I thought.

@FreedomBen I've created a PR in the relevant repository: [FreedomBen/dory-http-proxy #2](https://github.com/FreedomBen/dory-http-proxy/pull/2)

**Comment by FreedomBen** [comment]
Yeah, I really like this idea.  Will check out the PR, thank you!

**Comment by FreedomBen** [comment]
Thanks for your contribution :-)

Relevant PR has been merged, built, and pushed up to docker hub.

Dory has been updated to version 0.6.3 and now points at this image.  So everything should be good to go!

**Comment by ollietreend** [comment]
Happy to help @FreedomBen 👍 thanks for merging it in.

It'd probably be useful to mention xip.io support in the project's README, but I didn't get around to that. If I get some time I'll put something together.
