### ISSUE TITLE
Have to restart every few minutes

### ISSUE THREAD

**Issue by designfrontier** [FreedomBen/dory#18]
Running Docker Community edge
Version 17.11.0-ce-mac40 (20561)
Channel: edge
d8fd0f1f4a

on macOS 10.13.1 Beta (17B35a)

After a short period of time I have to do `dory down && dory up` to get routing going back to my docker containers. It's super weird, random and annoying :-)

I know this isn't a ton of details but I can dig up more.

**Comment by FreedomBen** [comment]
Interesting, thanks for the report.  If you think of it, could you run 
```dory attach nginx```
next time you notice this happening, and see if there are any helpful messages being printed in the nginx log output?

**Comment by designfrontier** [comment]
Seems to just hang on connecting to nginx... not sure why.
<img width="408" alt="screen shot 2017-12-04 at 10 19 24 pm" src="https://user-images.githubusercontent.com/422540/33591186-48b090cc-d941-11e7-90e6-c7f4891f2b1b.png">

**Comment by designfrontier** [comment]
Found this in the log this morning as it stalled out:

```
2017/12/05 05:22:04 [notice] 53#53: signal process started
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
dhparam generation complete, reloading nginx
```

**Comment by designfrontier** [comment]
Sorry for a million comments...

may be related to https://github.com/jwilder/nginx-proxy/issues/872 which seems to be a bug in nginx-proxy.

**Comment by FreedomBen** [comment]
Interesting, thanks!  Sometimes the `attach` seems to be hung but the proxy container just isn't writing anything to the log.  Usually I'll just make a request (with `curl` or my browser or something) to trigger some output.

**Comment by designfrontier** [comment]
This seems to have resolved with newer versions of docker... haven't had it pop up in a while. So I am going to close this :-)
