### ISSUE TITLE
Specify custom location of config file - option

### ISSUE THREAD

**Issue by andreyantipov** [FreedomBen/dory#20]
Hello, is it possible to specify location of config file instad using default ~/.dory.yml?

**Comment by FreedomBen** [comment]
Not currently, but this is a good idea.  The challenge will be that without a default file, you would have to tell Dory where the config file is somehow, so might need to pass a `-f <config-file>` flag each time.  That could easily be aliased so you don't have to type it tho.

Any suggestions on interface?  Would `-f config-file.yml` (plus `alias dory='dory -f config-file.yml'` in `~/.bashrc`)work for you?

**Comment by andreyantipov** [comment]
> Would -f config-file.yml (plus alias dory='dory -f config-file.yml' in ~/.bashrc)work for you?

Yeah!

> Any suggestions on interface?

What if also implement auto-search config (.dory.yml) initialiser method which recursively will search config in current working directory up to home directory (including it)? 

Something like that

```ruby
#!/usr/bin/env ruby

CONFIG = ".dory.yml"
HOME = ENV["HOME"]

config = catch (:config) do

	loop do
		# Search config file
		Dir.entries(Dir.pwd).each do |file|
			throw(:config, "#{Dir.pwd}/#{CONFIG}") if file === CONFIG
		end

		# Move up to HOME
		HOME === Dir.pwd ? throw(:config, false) : Dir.chdir("..")

	end #loop
end #:config

puts config
```

**Comment by FreedomBen** [comment]
Sorry for the delay, been super busy and sick.  Will work on this weekend tho.
