### ISSUE TITLE
Paswordless add resolver

### ISSUE THREAD

**Issue by beardcoder** [FreedomBen/dory#23]
To use paswordless resolver add we need to change `tee` to `/usr/bin/tee`
After this you can use the sudors 

```
 Cmnd_Alias DORY_EDIT_RESOLVCONF = /usr/bin/tee /etc/resolv.conf
 Cmnd_Alias DORY_EDIT_RESOLVDOCKER = /usr/bin/tee /etc/resolver/docker
 %admin ALL=(ALL) NOPASSWD: DORY_EDIT_RESOLVCONF, DORY_EDIT_RESOLVDOCKER
```

**Comment by FreedomBen** [comment]
I'm sorry but I'm not sure what the problem is.  Looking at the README.md, `tee` is already `/usr/bin/tee` .  Is there another place it needs to be updated?

**Comment by beardcoder** [comment]
Yes but if you use `tee` indeed of /usr/bin/tee the Cmnd_Alias is not working on macos 10.13.6

**Comment by FreedomBen** [comment]
Is there an issue with the documentation?

**Comment by FreedomBen** [comment]
Ah I see!  Thanks, I'll get a fix out
