### ISSUE TITLE
Docs, how to uninstall ;(

### ISSUE THREAD

**Issue by rayfoss** [FreedomBen/dory#42]
... I was quickly trying to setup Canvas and dory killed my entire network. It looks interesting... specially as a k8s dev. but I want to start over.

**How do we uninstall everything and fix NetworkManager/DNSMasq back to how it was?**

Does this run on Crostini/ChromeOS Debian linux VM's? I do most of my work on ChromeOS Linux

Step 1:
`sudo gem uninstall dory`  
Step 2: ?

**Comment by FreedomBen** [comment]
It's only a one way street!

Just kidding, it should be pretty easy.  If you run `dory down` it will clean up any containers it started, then you should be able to just `systemctl start NetworkManager` and dnsmasq.  

Dory only stops the service, she doesn't disable or change any config files or anything, so if you reboot it should be all back to normal.
