### ISSUE TITLE
[Question] New release/tags?

### ISSUE THREAD

**Issue by tripox** [FreedomBen/dory#48]
@FreedomBen, could you create a new tag/release from the latest code on master?

I'd like to see the `.dev` domain removed from the config and I see it's fixed on master (thanks, @rasben ❤️).

**Comment by FreedomBen** [comment]
Ah yes, will do.  Thanks for the reminder.

**Comment by tripox** [comment]
Nice, thank you for the tag and this great project, @FreedomBen!
