### ISSUE TITLE
Linux, Homebrew formula [Help needed]

### ISSUE THREAD

**Issue by tripox** [FreedomBen/dory#51]
I haven't been on Linux for a long time, so someone could might point me in the correct direction:
I tried spinning up a VM with Debian using Vagrant cloud and install docker and dory with Homebrew on Linux.

After installing dory with Homebrew I get the following when starting Dory: `invalid byte sequence in US-ASCII (ArgumentError)`.

I figured I had to do `sudo dpkg-reconfigure locales` and select `en_US.UTF-8`;  then I did `export LC_ALL="en_US.UTF-8"` and it worked perfectly.

Any idea what this could be and if it is usually necessary?
I have a feeling it's not correct to put it in the README or in the Brew formula but unsure what we be the best way to solve this.

**Comment by FreedomBen** [comment]
Thanks for working on this!  That locale issue that is commonly run into with the Debian docker image is rarely an issue on a real system, so I wouldn't worry about it too much.  On a normal system you're going to encounter serious problems with anything that links to glibc long before you try to run Dory.  Even if that isn't the case, it's definitely not a Dory-specific problem, so I wouldn't worry about putting that in the docs

**Comment by tripox** [comment]
Nice! Thank you :)
