### ISSUE TITLE
Add Ruby version required to README

### ISSUE THREAD

**Issue by fjagugar** [FreedomBen/dory#6]
I've tried to install dory using `gem install dory` using ruby 1.9 and ruby 2.0. In both cases, after installing, running any dory command threw a syntax error.

I've retried with ruby 2.3, and it worked.

I don't see any ruby related requirements in the README file. I would suggest to add some information about this.

**Comment by FreedomBen** [comment]
Oh yeah, good call.  I have CI set up for every ruby version starting with 2.1 and up (I use kwargs) so I'll add that to the README.  Thanks!
